var FLAGS={
	list:{
		actionsToGo:{
			audioOn:"none",
			audioOff:"none"
		},
		preparing:{
			flagIcon:"large",
		},
		condemned:{
			flagIcon:"large",
			audioOn:"condemned"
		},
		stealth:{
			flagIcon:"small"
		},
		rushing:{
			flagIcon:"small"
		},
		charge:{
			flagIcon:"small"
		},
		reborn:{
			flagIcon:"small"
		},
		taunt:{
			flagIcon:"small"
		},
		shield:{
			flagIcon:"small"
		},
		effect:{
			flagIcon:"small"
		},
		attackTwice:{
			flagIcon:"small"
		},
		lifeSteal:{
			flagIcon:"small"
		}
	},
	buffs:["actionsToGo","stealth","rushing","charge","reborn","taunt","shield"],
	debuffs:["condemned"],
	temporaryDebuffs:["preparing"],
}

var BEHAVIORS={

	// General
	card:{
		flags:{}		
	},
	paid:{
		onPlay:{
			condition:[
				{hasMana:1}
			],
			execute:[
				{payMana:1}
			]
		}
	},

	// Deployables
	deployable:{
		onPlay:{
			condition:[
				{canDeploy:1}
			],
			execute:[
				{deploy:1}				
			]			
		},
		onDeploy:{
			execute:[
				{
					targets:[{add:[{container:"card"}]}],
					do:[{to:"flag",attribute:"actionsToGo",action:"set"}]
				}
			]
		},
		onOpponentTurnStart:{
			execute:[
				{
					condition:[
						{isInto:"deployed"},
						{hasFlags:["condemned"]}
					],
					discard:1
				}
			]
		}
	},

	// Units
	unit:{
		image:{
			backgroundImage:"images/background-clouds",
			backgroundColor:"#f99"
		},
		frame:"unitframe",
		behavior:["card","paid","deployable","attacker"],
		onDeploy:{
			execute:[
				{
					condition:[
						{hasFlags:["charge","rushing"],not:1}
					],
					targets:[{add:[{container:"card"}]}],
					do:[{to:"flag",attribute:"preparing",action:"set"}]
				}
			]			
		},
		onAction:{
			execute:[
				{
					condition:[{hasFlags:["stealth"]}],
					targets:[{add:[{container:"card"}]}],
					do:[{to:"flag",attribute:"stealth",action:"unset"}]
				}
			]
		},
		onTurnStart:{
			execute:[
				{
					condition:[
						{isInto:"deployed"}
					],
					targets:[{add:[{container:"card"}]}],
					do:[{to:"flag",attribute:"preparing",action:"unset"}]
				}
			]
		},
		onTurnEnd:{
			execute:[
				{
					condition:[
						{isInto:"deployed"},
						{hasFlags:["rushing"]}
					],
					targets:[{add:[{container:"card"}]}],
					do:[{to:"flag",attribute:"rushing",action:"unset"}]
				},
				{
					condition:[
						{isInto:"deployed"},
						{hasFlags:["charge"]}
					],
					targets:[{add:[{container:"card"}]}],
					do:[{to:"flag",attribute:"charge",action:"unset"}]
				},
				{
					condition:[
						{isInto:"deployed"},
						{hasFlags:["preparing"]}
					],
					targets:[{add:[{container:"card"}]}],
					do:[{to:"flag",attribute:"preparing",action:"unset"}]
				},
				{
					condition:[
						{isInto:"deployed"}
					],
					targets:[{add:[{container:"card"}]}],
					do:[{to:"flag",attribute:"actionsToGo",action:"set"}]
				},
				{
					condition:[
						{isInto:"deployed"},
						{hasFlags:["attackTwice"]}
					],
					targets:[{add:[{container:"card"}]}],
					do:[{to:"flag",attribute:"actionsToGo",action:"+"}]
				}
			]
		},		
		onDead:{
			execute:[
				{discard:1}
			],
			then:[{
				condition:[
					{hasFlags:["reborn"]}
				],
				addCard:1,of:"self",toContainer:"deployed",
				andExecute:[
					{
						targets:[{add:[{container:"destination"}]}],
						do:[{to:"flag",attribute:"reborn",action:"unset"}]
					},
					{
						targets:[{add:[{container:"destination"}]}],
						do:[{to:"card",attribute:"health",action:"set",value:1}]
					}
				]
			}]
		}		
	},	

	// Units - Attacking
	attacker:{
		attackBack:true,
		onAction:{
			condition:[
				{has:["attack"]},
				{hasFlags:["preparing"],not:1},
				{hasFlags:["actionsToGo"]}
			],
			targets:[
				{
					add:[{side:"opponent",container:"deployed"}]
				},
				{
					condition:[{hasFlags:["rushing"],not:1}],
					add:[{side:"opponent",container:"hero"}]
				},
				{exclude:{flags:["stealth"]}},
				{exclusiveFlags:["taunt"]}
			],
			execute:[
				{attack:1},
				{
					targets:[{add:[{container:"card"}]}],
					do:[{to:"flag",attribute:"actionsToGo",action:"-"}]
				}
			]
		},
		onAttackBack:{
			targets:[
				{add:[{container:"destination"}]}
			],
			condition:[
				{has:["attack"]}
			],
			execute:[
				{attack:1}
			]
		}
	},	
	
	// Hero
	hero:{
		image:{
			backgroundImage:"images/background-clouds",
			backgroundColor:"#99f"
		},
		frame:"heroframe",
		behavior:["card","attacker"],
		flags:{hero:1},
		handLimit:7,
		deployLimit:7,
		armor:0,
		health:20,
		maxHealth:20,
		cost:10,
		attack:0,
		rules:{
			canDeploy:[
				{
					value1:{object:"side",attribute:"deployed",formula:"count"},
					is:"<",
					value2:{object:"hero",attribute:"deployLimit"}
				}				
			],
			canPick:[
				{
					value1:{object:"side",attribute:"hand",formula:"count"},
					is:"<",
					value2:{object:"hero",attribute:"handLimit"}
				}
			]
		},
		onDead:{
			execute:[
				{lose:1}
			]
		},
		onTurnStart:{
			execute:[
				{drawCards:1,gainMaxMana:1,restoreMana:1}
			]
		},
		onTurnEnd:{
			execute:[				
				{
					targets:[{add:[{container:"card"}]}],
					do:[{to:"flag",attribute:"actionsToGo",action:"set"}]
				}
			]
		},
		onGameStart:{
			execute:[
				{
					targets:[{add:[{container:"card"}]}],
					do:[{to:"flag",attribute:"actionsToGo",action:"set"}]
				},
				{drawCards:4}
			]
		},
		onAction:{
			then:[
				{broadcastEvent:"onHeroAttack"}
			]
		},
		onAttackBack:{
			then:[
				{broadcastEvent:"onHeroAttack"}
			]
		}
	},

	// Action cards
	action:{
		image:{
			backgroundImage:"images/background-clouds",
			backgroundColor:"#9f9"
		},
		frame:"actionframe",
		behavior:["card","paid"],
		onPlay:{
			execute:[
				{discard:1}
			]
		}
	},

	// Action cards - Targeting
	targetAllyUnits:{
		onPlay:{
			targets:[
				{add:[{container:"deployed"}]}
			]
		}
	},
	targetAllyHero:{
		onPlay:{
			targets:[
				{add:[{container:"hero"}]}
			]
		}
	},
	targetOpponentUnits:{
		onPlay:{
			targets:[
				{add:[{side:"opponent",container:"deployed",not:1,hasFlags:["stealth"]}]}
			]
		}
	},
	targetOpponentHero:{
		onPlay:{
			targets:[
				{add:[{side:"opponent",container:"hero",not:1,hasFlags:["stealth"]}]}
			]
		}
	},
	targetAlly:{
		behavior:["targetAllyUnits","targetAllyHero"]
	},
	targetOpponent:{
		behavior:["targetOpponentUnits","targetOpponentHero"]
	},
	targetUnits:{
		behavior:["targetAllyUnits","targetOpponentUnits"]
	},
	targetAny:{
		behavior:["targetOpponentUnits","targetOpponentHero","targetAllyHero","targetAllyUnits"]
	},

	// Equipment card
	equipment:{
		image:{
			backgroundImage:"images/background-clouds",
			backgroundColor:"#ff9"
		},
		frame:"equipframe",
		behavior:["card","paid"],
		onPlay:{
			execute:[
				{equip:1}
			]
		},
		onUnequip:{
			execute:[
				{discard:1}
			]
		},
		onNoPower:{
			execute:[
				{triggerEvent:"onUnequip"}
			]
		}
	},
	weapon:{
		equipmentSlot:"weapon",
		flags:{weapon:1},
		onHeroAttack:{
			condition:[
				{isInto:"equipment"}
			],
			execute:[
				{consumePower:1}
			]
		},
		onEquip:{
			execute:[
				{
					targets:[{add:[{container:"hero"}]}],
					do:[{
						to:"card",attribute:"attack",action:"+",
						value:{object:"card",attribute:"attack"}
					}]
				}
			]
		},
		onUnequip:{
			execute:[
				{
					targets:[{add:[{container:"hero"}]}],
					do:[{
						to:"card",attribute:"attack",action:"-",
						value:{object:"card",attribute:"attack"}
					}]
				}
			]
		}
	},

	// Traits
	traitAttackTwice:{
		flags:{attackTwice:1},
		labels:{
			EN:{
				description:"Attack twice each turn"
			},
			IT:{
				description:"Attacca due volte per turno"
			}
		}
	},
	traitStealth:{
		flags:{stealth:1},
		labels:{
			EN:{
				description:"Can't be attacked until his next attack"
			},
			IT:{
				description:"Non pu&ograve; essere attaccato prima del suo prossimo attacco"
			}
		}		
	},
	traitLifeSteal:{
		flags:{lifeSteal:1},
		labels:{
			EN:{
				description:"Inflicted damage heals you"
			},
			IT:{
				description:"Il danno inflitto ti cura"
			}
		}
	},
	traitCharge:{
		flags:{charge:1},
		labels:{
			EN:{
				description:"Can attack when played"
			},
			IT:{
				description:"Pu&ograve; attaccare quando giocato"
			}
		}
	},
	traitRush:{
		flags:{rushing:1},
		labels:{
			EN:{
				description:"Can attack units when played"
			},
			IT:{
				description:"Pu&ograve; attaccare le unit&agrave; quando giocato"
			}
		}		
	},
	traitTaunt:{
		flags:{taunt:1},
		labels:{
			EN:{
				description:"Attract melee attacks"
			},
			IT:{
				description:"Attira gli attacchi corpo a corpo"
			}
		}
	},
	traitReborn:{
		flags:{reborn:1},
		labels:{
			EN:{
				description:"Come back to life once with 1HP"
			},
			IT:{
				description:"Torna in vita con 1PV"
			}
		}
	},
	traitShield:{
		flags:{shield:1},
		labels:{
			EN:{
				description:"Ignore next damage"
			},
			IT:{
				description:"Ignora il prossimo danno"
			}
		}
	}

}

var CARDS={
	
	unitWarDog:{
		type:"unit",
		labels:{
			EN:{
				name:"War dog"
			},
			IT:{
				name:"Cane da guerra"
			}
		},
		image:{url:"images/unit-wardog"},
		cost:1,
		attack:1,
		health:1,
		behavior:["traitCharge","unit"],
	},
	unitFanatics:{
		type:"unit",
		labels:{
			EN:{
				name:"Fanatics",
				description:"When deployed can attack if weapon equipped"
			},
			IT:{
				name:"Fanatici",
				description:"Pu&ograve; attaccare quando schierato se un'arma &egrave; equipaggiata"
			}
		},
		onDeploy:{
			execute:[
				{
					condition:[
						{into:"equipment",hasFlags:["weapon"]}
					],
					targets:[{add:[{container:"card"}]}],
					do:[{to:"flag",attribute:"preparing",action:"unset"}]
				}
			]			
		},
		image:{url:"images/unit-fanatics"},
		cost:1,
		attack:2,
		health:1,
		behavior:["unit"],
	},
	unitKing:{
		type:"unit",
		labels:{
			EN:{
				name:"King",
				description:"When dead deploy a Burnt Banner 0/3 to opponent"
			},
			IT:{
				name:"Re",
				description:"Quando muore schiera uno Stendardo Bruciato 0/3 al nemico"
			}
		},
		onDead:{
			execute:[
				{to:"opponent",addCard:1,toContainer:"deployed",of:["unitBurntBanner"]}
			]
		},
		image:{url:"images/unit-king"},
		cost:1,
		attack:2,
		health:3,
		behavior:["unit"]
	},
	unitBurntBanner:{
		notCollectable:true,
		type:"unit",
		labels:{
			EN:{
				name:"Burnt Banner"
			},
			IT:{
				name:"Stendardo Bruciato"
			}
		},
		image:{url:"images/unit-burntbanner"},
		cost:0,
		attack:0,
		health:3,
		behavior:["traitTaunt","unit"]
	},
	unitRobot:{
		type:"unit",
		labels:{
			EN:{
				name:"Robot"
			},
			IT:{
				name:"Robot"
			}
		},
		image:{url:"images/unit-robot"},
		cost:1,
		attack:1,
		health:1,
		behavior:["traitReborn","unit"]
	},
	unitBatteringRam:{
		type:"unit",
		labels:{
			EN:{
				name:"Battering Ram"
			},
			IT:{
				name:"Ariete"
			}
		},
		image:{url:"images/unit-batteringram"},
		cost:1,
		attack:1,
		health:1,
		behavior:["traitRush","unit"],
	},
	unitFarmer:{
		type:"unit",
		labels:{
			EN:{
				name:"Farmer"
			},
			IT:{
				name:"Contadino"
			}
		},
		image:{url:"images/unit-farmer"},
		cost:0,
		attack:1,
		health:1,
		behavior:["unit"]
	},
	unitPlagueDoctor:{
		type:"unit",
		labels:{
			EN:{
				name:"Plague Doctor"
			},
			IT:{
				name:"Medico Della Peste"
			}
		},
		image:{url:"images/unit-plaguedoctor"},
		cost:1,
		attack:2,
		health:1,
		behavior:["traitLifeSteal","unit"]
	},
	unitInnkeeper:{
		type:"unit",
		labels:{
			EN:{
				name:"Innkeeper",
				description:"When played heal you 2HP"
			},
			IT:{
				name:"Locandiere",
				description:"Quando giocato ti cura 2PV"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[{add:[{container:"hero"}]}],
					do:[{action:"heal",value:2}]
				}
			]
		},
		image:{url:"images/unit-innkeeper"},
		cost:1,
		attack:2,
		health:1,
		behavior:["unit"]
	},
	unitGrenadier:{
		type:"unit",
		labels:{
			EN:{
				name:"Grenadier",
				description:"When dead deal 2 damage to opponent"
			},
			IT:{
				name:"Granatiere",
				description:"Quando muore infligge 2 danni al nemico"
			}
		},
		onDead:{
			execute:[
				{
					targets:[{add:[{side:"opponent",container:"hero"}]}],
					do:[{action:"dealDamage",value:2}]
				}
			]
		},
		image:{url:"images/unit-grenadier"},
		cost:1,
		attack:1,
		health:1,
		behavior:["unit"]
	},
	unitArcher:{
		type:"unit",
		labels:{
			EN:{
				name:"Archer"
			},
			IT:{
				name:"Arciere"
			}
		},
		image:{url:"images/unit-archer"},
		cost:1,
		attack:2,
		health:1,
		behavior:["traitStealth","unit"]
	},
	unitRecruit:{
		baseCard:true,
		type:"unit",
		labels:{
			EN:{
				name:"Recruit"
			},
			IT:{
				name:"Recluta"
			}
		},
		image:{url:"images/unit-recruit"},
		cost:1,
		attack:2,
		health:1,
		behavior:["unit"]
	},
	unitNinja:{
		type:"unit",
		labels:{
			EN:{
				name:"Ninja"
			},
			IT:{
				name:"Ninja"
			}
		},
		image:{url:"images/unit-ninja"},
		cost:1,
		attack:1,
		health:1,
		behavior:["traitAttackTwice","unit"]
	},
	unitFlagBearer:{
		type:"unit",
		labels:{
			EN:{
				name:"Flag Bearer",
				description:"When dead add a random 1 cost unit to hand"
			},
			IT:{
				name:"Portabandiera",
				description:"Quando muore aggiunge una carta casuale di valore 1 alla mano"
			}
		},
		onDead:{
			execute:[
				{addCard:1,toContainer:"hand",of:{fromCardsIndex:"units",withCost:1}}
			]
		},
		image:{url:"images/unit-flagbearer"},
		cost:1,
		attack:0,
		health:3,
		behavior:["unit"],
	},
	unitCombatMedic:{
		type:"unit",
		labels:{
			EN:{
				name:"Combat Medic",
				description:"Heal 2HP to all allies when played"
			},
			IT:{
				name:"Soccorritore Militare",
				description:"Cura 2PV a tutti gli alleati quando giocato"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[{add:[{container:"deployed"}]},{add:[{container:"hero"}]}],
					do:[{action:"heal",value:2}]
				}
			]
		},
		image:{url:"images/unit-combatmedic"},
		cost:1,
		attack:1,
		health:1,
		behavior:["unit"]
	},
	unitScarecrow:{
		baseCard:true,
		type:"unit",
		labels:{
			EN:{
				name:"Scarecrow"
			},
			IT:{
				name:"Spaventapasseri"
			}
		},
		image:{url:"images/unit-scarecrow"},
		cost:1,
		attack:0,
		health:4,
		behavior:["traitTaunt","unit"]
	},
	unitCoPilot:{
		notCollectable:true,
		type:"unit",
		labels:{
			EN:{
				name:"Co-pilot"
			},
			IT:{
				name:"Copilota"
			}
		},
		image:{url:"images/unit-copilot"},
		cost:0,
		attack:1,
		health:1,
		behavior:["unit"]
	},
	unitSidecar:{
		type:"unit",
		labels:{
			EN:{
				name:"Sidecar",
				description:"When dead deploy a 1/1 Co-pilot"
			},
			IT:{
				name:"Sidecar",
				description:"Quando muore schiera un 1/1 Copilota"
			}
		},
		onDead:{
			execute:[
				{addCard:1,toContainer:"deployed",of:["unitCoPilot"]}
			]
		},
		image:{url:"images/unit-sidecar"},
		cost:1,
		attack:1,
		health:1,
		behavior:["unit"]
	},
	unitArmoredSoldier:{
		type:"unit",
		labels:{
			EN:{
				name:"Armored Soldier"
			},
			IT:{
				name:"Soldato In Armatura"
			}
		},
		image:{url:"images/unit-armoredsoldier"},
		cost:1,
		attack:1,
		health:1,
		behavior:["traitShield","unit"]
	},
	unitDrone:{
		type:"unit",
		labels:{
			EN:{
				name:"Drone"
			},
			IT:{
				name:"Drone"
			}
		},
		image:{url:"images/unit-drone"},
		cost:1,
		attack:1,
		health:2,
		behavior:["traitTaunt","unit"]
	},
	unitDeliveryGuy:{
		type:"unit",
		labels:{
			EN:{
				name:"Delivery Guy",
				description:"When deployed gives +1/+1 to another unit"
			},
			IT:{
				name:"Fattorino",
				description:"Quando schierata concede +1/+1 a un'altra unit&agrave;"
			}
		},
		onDeploy:{
			execute:[
				{
					targets:[
						{add:[{container:"deployed",isNotMe:1}]},
						{someRandomly:1}
					],
					do:[
						{
							to:"card",attribute:"attack",action:"+",
							value:1
						},{
							action:"heal",value:1
						}
					]
				}
			]
		},
		image:{url:"images/unit-deliveryguy"},
		cost:1,
		attack:1,
		health:1,
		behavior:["unit"]
	},
	unitBarbarian:{
		type:"unit",
		labels:{
			EN:{
				name:"Barbarian",
				description:"On overkill this unit gain 5 attack"
			},
			IT:{
				name:"Barbaro",
				description:"Quando ultra-uccide questa unit&agrave; guadagna 5 di attacco"
			}
		},
		onOverkill:{
			execute:[
				{
					targets:[{add:[{container:"card"}]}],
					do:[{action:"+",to:"card",attribute:"attack",value:5}]
				}
			]
		},
		image:{url:"images/unit-barbarian"},
		cost:1,
		attack:1,
		health:1,
		behavior:["unit"]
	},
	unitSaboteur:{
		type:"unit",
		labels:{
			EN:{
				name:"Saboteur",
				description:"When deployed deal 1 damage to opponent"
			},
			IT:{
				name:"Sabotatore",
				description:"Quando schierato fa 1 danno all'avversario"
			}
		},
		onDeploy:{
			execute:[
				{
					targets:[{add:[{side:"opponent",container:"hero"}]}],
					do:[{action:"dealDamage",value:1}]
				}
			]
		},
		image:{url:"images/unit-saboteur"},
		cost:1,
		attack:1,
		health:1,
		behavior:["unit"]
	},
	unitKamikaze:{
		type:"unit",
		labels:{
			EN:{
				name:"Kamikaze",
				description:"When dead deal 2 damage to opponent"
			},
			IT:{
				name:"Kamikaze",
				description:"Quando muore fa 2 danni all'avversario"
			}
		},
		onDead:{
			execute:[
				{
					targets:[{add:[{side:"opponent",container:"hero"}]}],
					do:[{action:"dealDamage",value:2}]
				}
			]
		},
		image:{url:"images/unit-kamikaze"},
		cost:1,
		attack:0,
		health:2,
		behavior:["unit"]
	},
	unitWitchDoctor:{
		type:"unit",
		labels:{
			EN:{
				name:"Witch Doctor",
				description:"Heal you 1HP at the beginning of your turn"
			},
			IT:{
				name:"Stregone",
				description:"Ti cura 1PV all'inizio del tuo turno"
			}
		},
		onTurnStart:{
			execute:[
				{
					condition:[
						{isInto:"deployed"}
					],
					targets:[{add:[{container:"hero"}]}],
					do:[{action:"heal",value:1}]
				}
			]
		},
		image:{url:"images/unit-witchdoctor"},
		cost:1,
		attack:1,
		health:2,
		behavior:["unit"]
	},
	unitBlacksmith:{
		type:"unit",
		labels:{
			EN:{
				name:"Blacksmith",
				description:"When dead add a random 1 cost unit to hand"
			},
			IT:{
				name:"Fabbro",
				description:"Quando muore aggiunge una carta casuale di valore 1 alla mano"
			}
		},
		onDead:{
			execute:[
				{addCard:1,toContainer:"hand",of:{fromCardsIndex:"units",withCost:1}}
			]
		},
		image:{url:"images/unit-blacksmith"},
		cost:1,
		attack:1,
		health:2,
		behavior:["unit"]
	},
	unitRioter:{
		type:"unit",
		labels:{
			EN:{
				name:"Rioter",
				description:"Other Rioters earn 1 attack"
			},
			IT:{
				name:"Rivoltoso",
				description:"Gli altri Rivoltosi guadagnano 1 attacco"
			}
		},
		flags:{effect:1},
		onDeploy:{
			execute:[
				{
					setEffect:{
						targets:[{add:[{container:"deployed",isId:"unitRioter"}]}],
						on:[
							{
								targets:[{add:[{container:"card"}]}],
								do:[{to:"card",attribute:"attack",action:"+"}]
							}
						],
						off:[
							{
								targets:[{add:[{container:"card"}]}],
								do:[{to:"card",attribute:"attack",action:"-"}]
							}
						]
					}
				}
			]
		},
		onDiscard:{
			execute:[
				{
					unsetEffect:1
				}
			]
		},
		image:{url:"images/unit-rioter"},
		cost:1,
		attack:1,
		health:1,
		behavior:["unit"]
	},
	unitMajorette:{
		type:"unit",
		labels:{
			EN:{
				name:"Majorette",
				description:"When deployed gives +2 attack to another unit for this turn"
			},
			IT:{
				name:"Majorette",
				description:"Quando schierato da +2 attacco a un'altra unit&agrave; per questo turno"
			}
		},
		onDeploy:{
			execute:[
				{
					setEffect:{
						justOnce:true,
						targets:[
							{add:[{container:"deployed",isNotMe:1}]},
							{someRandomly:1}
						],
						on:[
							{
								targets:[{add:[{container:"card"}]}],
								do:[{to:"card",attribute:"attack",action:"+",value:2}]
							}
						],
						off:[
							{
								targets:[{add:[{container:"card"}]}],
								do:[{to:"card",attribute:"attack",action:"-",value:2}]
							}
						]
					}
				}
			]
		},
		onTurnEnd:{
			execute:[
				{unsetEffect:1}
			]
		},
		onDiscard:{
			execute:[
				{unsetEffect:1}
			]
		},
		image:{url:"images/unit-majorette"},
		cost:1,
		attack:1,
		health:1,
		behavior:["unit"]
	},
	actionCoffee:{
		type:"action",
		labels:{
			EN:{
				name:"Coffee",
				description:"Awake a unit and gives Rush"
			},
			IT:{
				name:"Caff&egrave;",
				description:"Sveglia un'unit&agrave; e assegna Frenesia"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[{add:[{container:"destination"}]}],
					do:[
						{to:"flag",attribute:"rushing",action:"set"},
						{to:"flag",attribute:"preparing",action:"unset"}
					]
				}
			]
		},
		image:{url:"images/action-coffee"},
		cost:1,
		behavior:["action","targetAllyUnits"]
	},
	actionBalista:{
		type:"action",
		labels:{
			EN:{
				name:"Balista",
				description:"Deal 3 damage to opponent"
			},
			IT:{
				name:"Ballista",
				description:"Infligge 3 danni al nemico"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[
						{add:[{side:"opponent",container:"hero"}]}
					],
					do:[{action:"dealDamage",value:3}]
				}
			]
		},
		image:{url:"images/action-balista"},
		cost:1,
		behavior:["action"]
	},
	actionCatapult:{
		type:"action",
		labels:{
			EN:{
				name:"Catapult",
				description:"Deal 4 damage and discard a card from hand"
			},
			IT:{
				name:"Catapulta",
				description:"Infligge 4 danni e scarta una carta dalla mano"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[{add:[{container:"destination"}]}],
					do:[{action:"dealDamage",value:4}]
				},
				{
					targets:[
						{add:[{container:"hand",isNotMe:1}]},
						{someRandomly:1}
					],
					do:[
						{action:"discard"}
					]
				}
			]
		},
		image:{url:"images/action-catapult"},
		cost:1,
		behavior:["action","targetAny"]
	},
	actionCamera:{
		type:"action",
		labels:{
			EN:{
				name:"Camera",
				description:"Add a copy of one opponent hand card in yours"
			},
			IT:{
				name:"Videocamera",
				description:"Aggiungi una copia di una carta in mano all'avversario alla tua"
			}
		},
		onPlay:{
			execute:[
				{addCard:1,toContainer:"hand",of:{
					targets:[
						{add:[{side:"opponent",container:"hand"}]},
						{someRandomly:1}
					]
				}}
			]
		},
		image:{url:"images/action-camera"},
		cost:1,
		behavior:["action"]
	},
	actionBounty:{
		type:"action",
		labels:{
			EN:{
				name:"Bounty",
				description:"Destroy an opponent unit when your next turn starts"
			},
			IT:{
				name:"Taglia",
				description:"Distruggi un'unit&agrave; avversaria all'inizio del tuo prossimo turno"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[{add:[{container:"destination"}]}],
					do:[{to:"flag",attribute:"condemned",action:"set"}]
				}
			]
		},
		image:{url:"images/action-bounty"},
		cost:1,
		behavior:["action","targetOpponentUnits"]
	},
	actionJammer:{
		type:"action",
		labels:{
			EN:{
				name:"Jammer",
				description:"Deploy 2 0/2 Fake Recruit with Taunt"
			},
			IT:{
				name:"Jammer",
				description:"Schiera 2 0/2 Finta Recluta con Provocazione"
			}
		},
		onPlay:{
			execute:[
				{addCard:2,toContainer:"deployed",of:["unitFakeRecruit"]}
			]
		},
		image:{url:"images/action-jammer"},
		cost:1,
		behavior:["action"]
	},
	unitFakeRecruit:{
		notCollectable:true,
		type:"unit",
		labels:{
			EN:{
				name:"Fake Recruit"
			},
			IT:{
				name:"Finta Recluta"
			}
		},
		image:{url:"images/unit-fakerecruit"},
		cost:0,
		attack:0,
		health:2,
		behavior:["traitTaunt","unit"]
	},
	actionAdrenalineShot:{
		type:"action",
		labels:{
			EN:{
				name:"Adrenaline Shot",
				description:"Fully heal your units and give Taunt"
			},
			IT:{
				name:"Adrenalina",
				description:"Cura interamente le tue unit&agrave; e da Provocazione"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[{add:[{container:"deployed"}]}],
					do:[
						{action:"heal",value:{object:"target",attribute:"maxHealth"}},
						{to:"flag",attribute:"taunt",action:"set"}
					]
				}
			]
		},
		image:{url:"images/action-adrenalineshot"},
		cost:0,
		behavior:["action"]
	},
	actionSharpeningStone:{
		type:"action",
		labels:{
			EN:{
				name:"Sharpening Stone",
				description:"Gives +2 attack to equipped weapon"
			},
			IT:{
				name:"Cote",
				description:"Concede +2 di attacco all'arma equipaggiata"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[{add:[{container:"equipment",hasFlags:["weapon"]}]}],
					do:[
						{
							to:"card",attribute:"attack",action:"+",
							value:2
						}
					]
				},
				{
					condition:[
						{into:"equipment",hasFlags:["weapon"]}
					],
					targets:[{add:[{container:"hero"}]}],
					do:[
						{
							to:"card",attribute:"attack",action:"+",
							value:2
						}
					]
				}
			]
		},
		image:{url:"images/action-cote"},
		cost:1,
		behavior:["action"]
	},
	actionBarbedWire:{
		type:"action",
		labels:{
			EN:{
				name:"Barbed Wire",
				description:"You earn +2 attack for this turn and +2 armor"
			},
			IT:{
				name:"Filo Spinato",
				description:"Guadagni +2 di attacco per questo turno e +2 di armatura"
			}
		},
		onPlay:{
			execute:[
				{equip:1},
				{
					targets:[{add:[{container:"hero"}]}],
					do:[
						{
							to:"card",attribute:"attack",action:"+",
							value:2
						}
					]
				},
				{
					targets:[{add:[{container:"hero"}]}],
					do:[
						{
							to:"card",attribute:"armor",action:"+",
							value:2
						}
					]
				}
			]
		},
		onTurnEnd:{
			execute:[
				{
					condition:[{isInto:"equipment"}],
					targets:[{add:[{container:"hero"}]}],
					do:[
						{
							to:"card",attribute:"attack",action:"-",
							value:2
						}
					]
				},
				{
					condition:[{isInto:"equipment"}],
					discard:1
				}
			]
		},
		image:{url:"images/action-barbedwire"},
		cost:1,
		behavior:["action"]
	},
	actionWhiskey:{
		type:"action",
		labels:{
			EN:{
				name:"Whiskey",
				description:"Gives +3 attack to a unit"
			},
			IT:{
				name:"Whiskey",
				description:"Concede +3 di attacco a un'unit&agrave;"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[{add:[{container:"destination"}]}],
					do:[
						{
							to:"card",attribute:"attack",action:"+",
							value:3
						}
					]
				}
			]
		},
		image:{url:"images/action-whiskey"},
		cost:1,
		behavior:["action","targetUnits"]
	},
	actionMolotov:{
		type:"action",
		labels:{
			EN:{
				name:"Molotov cocktail",
				description:"Deal 1 damage to a random enemy 3 times"
			},
			IT:{
				name:"Molotov cocktail",
				description:"Infligge 1 danno a un'unit&agrave; nemica casuale 3 volte"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[
						{add:[
							{side:"opponent",container:"deployed"},
							{side:"opponent",container:"hero"}
						]},
						{someRandomly:1}
					],
					do:[{action:"dealDamage",value:1}]
				},
				{
					targets:[
						{add:[
							{side:"opponent",container:"deployed"},
							{side:"opponent",container:"hero"}
						]},
						{someRandomly:1}
					],
					do:[{action:"dealDamage",value:1}]
				},
				{
					targets:[
						{add:[
							{side:"opponent",container:"deployed"},
							{side:"opponent",container:"hero"}
						]},
						{someRandomly:1}
					],
					do:[{action:"dealDamage",value:1}]
				}
			]
		},		
		image:{url:"images/action-molotov"},
		cost:1,
		behavior:["action"]
	},
	actionMedikit:{
		type:"action",
		labels:{
			EN:{
				name:"Medikit",
				description:"Heal you 5HP"
			},
			IT:{
				name:"Kit Medico",
				description:"Ti cura di 5PV"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[
						{add:[{container:"hero"}]}
					],
					do:[{action:"heal",value:5}]
				}
			]
		},
		image:{url:"images/action-medikit"},
		cost:1,
		behavior:["action"]
	},
	actionWhip:{
		type:"action",
		labels:{
			EN:{
				name:"Whip",
				description:"Set a unit attack to 1"
			},
			IT:{
				name:"Frusta",
				description:"Imposta l'attacco di un'unit&agrave; a 1"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[{add:[{container:"destination"}]}],
					do:[{to:"card",attribute:"attack",action:"set",value:1}]
				}
			]
		},
		image:{url:"images/action-whip"},
		cost:1,
		behavior:["action","targetUnits"]
	},
	actionShield:{
		type:"action",
		labels:{
			EN:{
				name:"Shield",
				description:"Gives Shield to a unit"
			},
			IT:{
				name:"Scudo",
				description:"Assegna Scudo a un'unit&agrave;"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[{add:[{container:"destination"}]}],
					do:[{to:"flag",attribute:"shield",action:"set"}]
				}
			]
		},
		image:{url:"images/action-shield"},
		cost:1,
		behavior:["action","targetUnits"]
	},
	actionBomb:{
		type:"action",
		labels:{
			EN:{
				name:"Bomb",
				description:"Deal 1 damage to ALL units"
			},
			IT:{
				name:"Bomba",
				description:"Infligge 1 danno a TUTTE le unit&agrave;"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[
						{add:[
							{container:"deployed"},
							{side:"opponent",container:"deployed"}
						]}
					],
					do:[{action:"dealDamage",value:1}]
				}
			]
		},
		image:{url:"images/action-bomb"},
		cost:1,
		behavior:["action"]
	},
	actionShuriken:{
		type:"action",
		labels:{
			EN:{
				name:"Shuriken",
				description:"Deal 3 damage to a unit"
			},
			IT:{
				name:"Shuriken",
				description:"Infligge 3 danni a un'unit&agrave;"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[{add:[{container:"destination"}]}],
					do:[{action:"dealDamage",value:3}]
				}
			]
		},
		image:{url:"images/action-shuriken"},
		cost:1,
		behavior:["action","targetUnits"]
	},
	unitMercenary:{
		type:"unit",
		labels:{
			EN:{
				name:"Mercenary"
			},
			IT:{
				name:"Mercenario"
			}
		},
		image:{url:"images/unit-mercenary"},
		cost:1,
		attack:2,
		health:2,
		behavior:["unit"]
	},
	unitNurse:{
		type:"unit",
		labels:{
			EN:{
				name:"Nurse",
				description:"When deployed gives +2HP to another unit"
			},
			IT:{
				name:"Nurse",
				description:"Quando schierato concede +2PV a un'altra unit&agrave;"
			}
		},
		onDeploy:{
			execute:[
				{
					targets:[
						{add:[{container:"deployed",isNotMe:1}]},
						{someRandomly:1}
					],
					do:[
						{
							action:"heal",value:2
						}
					]
				}
			]
		},
		image:{url:"images/unit-nurse"},
		cost:1,
		attack:1,
		health:1,
		behavior:["unit"]
	},

	unitHero:{
		type:"unit",
		labels:{
			EN:{
				name:"Hero",
				description:"When dead decrease your hand units cost by 1"
			},
			IT:{
				name:"Eroe",
				description:"Quando muore riudce il costo delle unit&agrave; in mano di 1"
			}
		},
		onDead:{
			execute:[
				{
					targets:[{add:[{container:"hand",isType:"unit"}]}],
					do:[{action:"-",to:"card",attribute:"cost"}]
				}
			]
		},
		image:{url:"images/unit-hero"},
		cost:1,
		attack:1,
		health:2,
		behavior:["unit"]
	},
	actionLandmine:{
		type:"action",
		labels:{
			EN:{
				name:"Land mine",
				description:"Deal 2 damage to one undamaged units"
			},
			IT:{
				name:"Mina",
				description:"Infligge 2 danni a un'unit&agrave; danneggiata"
			}
		},
		onPlay:{
			targets:[
				{add:[{side:"opponent",container:"deployed",isDamaged:false}]}
			],
			execute:[
				{
					targets:[{add:[{container:"destination"}]}],
					do:[{action:"dealDamage",value:2}]
				}
			]
		},
		image:{url:"images/action-landmine"},
		cost:0,
		behavior:["action"]
	},
	actionBandages:{
		type:"action",
		labels:{
			EN:{
				name:"Bandages",
				description:"Heal 2HP to a unit"
			},
			IT:{
				name:"Bende",
				description:"Cura di 2PV un'unit&agrave;"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[{add:[{container:"destination"}]}],
					do:[{action:"heal",value:2}]
				}
			]
		},
		image:{url:"images/action-bandages"},
		cost:0,
		behavior:["action","targetUnits"]
	},
	actionCoin:{
		type:"action",
		labels:{
			EN:{
				name:"Coin",
				description:"Earn 1 Mana for this turn"
			},
			IT:{
				name:"Moneta",
				description:"Guadagna 1 Mana per questo turno"
			}
		},
		onPlay:{
			execute:[
				{gainMana:1}
			]
		},
		image:{url:"images/action-coin"},
		cost:0,
		behavior:["action"]
	},
	actionDart:{
		baseCard:true,
		type:"action",
		labels:{
			EN:{
				name:"Dart",
				description:"Deal 1 damage"
			},
			IT:{
				name:"Dardo",
				description:"Infligge 1 danno"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[{add:[{container:"destination"}]}],
					do:[{action:"dealDamage",value:1}]
				}
			]
		},
		image:{url:"images/action-dart"},
		cost:0,
		behavior:["action","targetAny"]
	},
	leaderTech:{
		type:"hero",
		labels:{
			EN:{
				name:"Tech"
			},
			IT:{
				name:"Tech"
			}
		},
		sideColor:"#f48b74",
		image:{url:"images/leader-tech"},		
		behavior:["hero"]
	},
	leaderImpera:{
		type:"hero",
		labels:{
			EN:{
				name:"Impera"
			},
			IT:{
				name:"Impera"
			}
		},
		sideColor:"#d7ed74",
		image:{url:"images/leader-impera"},
		behavior:["hero"]
	},
	leaderCult:{
		type:"hero",
		labels:{
			EN:{
				name:"Cult"
			},
			IT:{
				name:"Cult"
			}
		},
		sideColor:"#33e474",
		image:{url:"images/leader-cult"},
		behavior:["hero"]
	},
	leaderArt:{
		baseCard:true,
		type:"hero",
		labels:{
			EN:{
				name:"Art"
			},
			IT:{
				name:"Art"
			}
		},
		sideColor:"#d78b74",
		image:{url:"images/leader-art"},
		behavior:["hero"]
	},
	leaderPragma:{
		type:"hero",
		labels:{
			EN:{
				name:"Pragma"
			},
			IT:{
				name:"Pragma"
			}
		},
		sideColor:"#d78b39",
		image:{url:"images/leader-pragma"},
		behavior:["hero"]
	},
	leaderEgal:{
		type:"hero",
		labels:{
			EN:{
				name:"Egal"
			},
			IT:{
				name:"Egal"
			}
		},
		sideColor:"#3f8b74",
		image:{url:"images/leader-egal"},
		behavior:["hero"]
	},
	actionGrapplingHook:{
		type:"action",
		labels:{
			EN:{
				name:"Grappling Hook",
				description:"Deal 1 damage to a unit, if kills it draw a card"
			},
			IT:{
				name:"Rampino",
				description:"Infligge 1 danno a una unit&agrave;, se la uccide pesca una carta"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[{add:[{container:"destination"}]}],
					do:[{action:"dealDamage",value:1}]
				}
			]
		},
		onKill:{
			execute:[
				{drawCards:1}
			]
		},
		image:{url:"images/action-grapplinghook"},
		cost:1,
		behavior:["action","targetUnits"]
	},
	weaponSniperRifle:{
		type:"equipment",
		labels:{
			EN:{
				name:"Sniper Rifle"
			},
			IT:{
				name:"Fucile Di Precisione"
			}
		},
		image:{url:"images/weapon-sniperrifle"},
		cost:5,
		attack:5,
		power:2,
		behavior:["equipment","weapon"]
	},
	actionFootholdTrap:{
		type:"action",
		labels:{
			EN:{
				name:"Foothold Trap",
				description:"Deal 2 damage"
			},
			IT:{
				name:"Tagliola",
				description:"Infligge 2 danni"
			}
		},
		onPlay:{
			execute:[
				{
					targets:[{add:[{container:"destination"}]}],
					do:[{action:"dealDamage",value:2}]
				}
			]
		},		
		image:{url:"images/action-trap"},
		cost:1,
		behavior:["action","targetAny"]
	},
	weaponGun:{
		type:"equipment",
		labels:{
			EN:{
				name:"Gun"
			},
			IT:{
				name:"Pistola"
			}
		},
		image:{url:"images/weapon-gun"},
		cost:5,
		attack:3,
		power:4,
		behavior:["equipment","weapon"]
	},
	weaponAxe:{
		baseCard:true,
		type:"equipment",
		labels:{
			EN:{
				name:"Axe"
			},
			IT:{
				name:"Ascia"
			}
		},
		image:{url:"images/weapon-axe"},
		cost:3,
		attack:2,
		power:2,
		behavior:["equipment","weapon"]
	},
	weaponSword:{
		type:"equipment",
		labels:{
			EN:{
				name:"Sword",
				description:"Heal 2HP every attack"
			},
			IT:{
				name:"Spada",
				description:"Cura 2PV a ogni attacco"
			}
		},
		image:{url:"images/weapon-sword"},
		cost:4,
		attack:4,
		power:2,
		behavior:["equipment","weapon"],
		onHeroAttack:{
			condition:[
				{isInto:"equipment"}
			],
			execute:[
				{
					targets:[{add:[{container:"hero"}]}],
					do:[{action:"heal",value:2}]
				}
			]
		}
	},
	weaponBoomerang:{
		type:"equipment",
		labels:{
			EN:{
				name:"Boomerang",
				description:"Inflicted damage heals you"
			},
			IT:{
				name:"Boomerang",
				description:"I danni inflitti ti curano"
			}
		},
		image:{url:"images/weapon-boomerang"},
		cost:3,
		attack:2,
		power:2,
		behavior:["equipment","weapon"],
		onEquip:{
			execute:[
				{
					targets:[{add:[{container:"hero"}]}],
					do:[{
						to:"flag",attribute:"lifeSteal",action:"+"
					}]
				}
			]
		},
		onUnequip:{
			execute:[
				{
					targets:[{add:[{container:"hero"}]}],
					do:[{
						to:"flag",attribute:"lifeSteal",action:"-"
					}]
				}
			]
		}
	},
	weaponKnife:{
		type:"equipment",
		labels:{
			EN:{
				name:"Knife"
			},
			IT:{
				name:"Coltello"
			}
		},
		image:{url:"images/weapon-knife"},
		cost:1,
		attack:1,
		power:4,
		behavior:["equipment","weapon"]
	}

}